name: Deploy Website

on:
  push:
    branches: [ main ]
    

jobs:
  
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 16
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./ bootcamp-2020-html-page.surge.sh --token ${{secrets.SURGE_TOKEN}}
